#!/usr/bin/env ruby
branch_limit = `git config --get recent.limit 2>/dev/null`.to_i
branch_limit = 10 if branch_limit == 0

show_current_branch = (`git config --get recent.showcurrent 2>/dev/null`.to_i == 1) ? true : false
current_branch = `git rev-parse --abbrev-ref HEAD 2>/dev/null`.chomp
all_branches = `git reflog 2>/dev/null | \\grep -Pio "moving from ([^\\s]+)" | \\awk '{ print $3 }' | \\grep -Piv "[0-9a-f]{40}"`.split("\n")

if all_branches.length == 0
  puts "No recently viewed branches"
  exit
end

if !show_current_branch
  all_branches.delete_if { |value| value == current_branch }
end

recent_branches = all_branches.uniq.slice(0..branch_limit-1)

if !ARGV[0].nil?
  selectedBranch = ARGV[0].to_i
  if (selectedBranch < branch_limit) && (selectedBranch >= 0)
    `git checkout #{recent_branches[selectedBranch]}`
    exit
  else
    puts "Branch number out of range 0-#{branch_limit-1}"
    exit
  end
end

number = 0
recent_branches.each do |branchName|
  puts "[#{number}] #{branchName}"
  number += 1
end

print "Branch number: "
desired_branch = gets.chomp
exit if desired_branch.empty?

desired_branch = desired_branch.to_i

if (desired_branch < branch_limit) && (desired_branch >= 0)
  `git checkout #{recent_branches[desired_branch]}`
  exit
else
  puts "Branch number out of range 0-#{branch_limit-1}"
end